### ISSUE TITLE
linuxdeployqt issue?

### ISSUE THREAD

**Issue by probonopd** [Areon1031/CPE_631_Advanced_Computer_Architecture#1]
https://github.com/Areon1031/CPE_631_Advanced_Computer_Architecture/blob/79b10c981a15c929e99e237313a1c45233439b04/Project/Notes/DeploymentInformation#L8

If this is needed, then this is a bug in [linuxdeployqt](https://github.com/probonopd/linuxdeployqt/). Please [open an issue there](https://github.com/probonopd/linuxdeployqt/issues) indicating how to reproduce this. Thanks.

**Comment by sp00k1031** [comment]
Hello,

This isn't an issue and this workaround was created to fix an error on my
end.  I had originally had this workaround when trying to deploy on Ubuntu
17.10.  I created this file to remind me of the workaround and lazily added
it to my class repository, the issue has since been resolved and I've
removed this file as the workaround is not needed.  Also, thanks for the
tool and the help topics relating to building on Trusty, this helped a lot
for my class project as my Ubuntu 17.10 AppImage would not run on our lab
computers because of dependency issues.  I'm new to AppImages and the
documentation provided by you was very helpful.

Thanks for checking in and keep up the good work,
Kyle Ray

P.S. Please excuse my repository etiquette as this is a catch all for my
classes.  Even though it is public I didn't intend for anyone to actually
peruse their contents =P.

**Comment by probonopd** [comment]
Thank you very much. Just wanted to make sure we solve `linuxdeployqt` issues, but if it's not a `linuxdeployqt` issue, then I'm also happy ;-) Thanks for using linuxdeployqt and AppImage.
